name: PHP Coding Standards Check
run-name: ${{ github.actor }} is checking coding standards
on:
  push:
    paths:
      - server.php
      - .github/workflows/phpcs.yml
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by a ${{ github.event_name }} event."
      - run: echo "Running on a ${{ runner.os }} "
      - run: echo "Current branch => ${{ github.ref }} on ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install PHP
        run: |
          sudo apt install php
      - name: Install phpcs
        run: |
          sudo apt install php-codesniffer
      - name: Check coding standard
        run: phpcs --standard=PSR12 .
      - run: echo "${{ job.status }}"